global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'express-backend'
    static_configs:
      - targets: ['backend:3000']
